project:
  type: book
  output-dir: docs

book:
  title: Dracula
  subtitle: A Computational Scholarly Edition
  author: 
    - name: 
        given: Bram
        family: Stoker
  date: last-modified
  date-format: "YYYY"
  abstract: |
    This edition of Bram Stoker's Dracula presents the original text alongside computational analyses and visualizations of it to enable one to explore the book via close readings and distant reading. The analyses include sentiment analysis and mapping of place references in the book sized by number of references. The book is intended for scholars and students of literature, as well as anyone interested in digital humanities and the intersection of literature and data science.
  description: |
    An edition of Bram Stoker's Dracula that presents the original text alongside computational analyses and visualizations of it.
  cover-image: Dracula_cover.jpg
  cover-image-alt: book cover of Dracula with a yellow background and red title, author, and border
  editor: Adam Mazel
  original-author: Bram Stoker
  original-date: 1897
  original-publisher: Archibald Constable and Company
  original-publisher-place: Westminster & Whitehall Gardens
  favicon: Dracula_cover.jpg
  site-url: https://iulibscholcomm.github.io/dracula/
  search: 
    location: sidebar
    type: textbox
    copy-button: true
    show-item-context: true
  page-navigation: true
  back-to-top-navigation: true
  image: Dracula_cover.jpg
  image-alt: book cover of Dracula with a yellow background and red title, author, and border
  bread-crumbs: true
  twitter-card: true
  open-graph: true
  sidebar: 
    aria-label: Contents
    style: docked
    collapse-level: 1
    pinned: true
    logo: Dracula_cover.jpg
    logo-alt: book cover of Dracula with a yellow background and red title, author, and border
  repo-url: https://github.com/IULibScholComm/dracula
  

  chapters: 
    - index.qmd
    - note.qmd
    - 1.qmd
    - 2.qmd
    - 3.qmd
    - 99-text-analysis.qmd
  code-links: binder

format:
  html:
    theme:
      - cosmo
      - brand
    anchor-sections: true
    tabsets: true
    respect-user-color-scheme: true
    html-q-tags: true
    smooth-scroll: true
    section-divs: true
    toc: true
    page-layout: article
    title-block-style: default
    lightbox: true
    link-external-newwindow: true
    format-links: true
    lang: "en-US"
    number-sections: true
    fig-cap-location: margin
    code-fold: true
    code-summary: "Show / Hide Code"
    code-overflow: wrap
    code-line-numbers: true
    code-copy: true
    code-block-border-left: true
    cache: false
    eval: true
    echo: false
    output: true
    warning: false
    error: false
    freeze: auto



